# copied directly from Colby's previous work:  https://github.com/covid19risk/legacy_website/blob/12ebd1324c1c03bdab90c9522ecabbf6f9e53014/.github/workflows/airtable.yaml

name: Airtable

on:
  schedule: 
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

     - name: Create hotfix branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "octocat"
          git checkout -b "auto-add-news"

      - name: Run airtable script
        env:
          AIRTABLE_BASE_KEY: ${{ secrets.AIRTABLE_BASE_KEY }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }} 
        working-directory: scripts
        run: |
          pip3 install airtable-python-wrapper
          chmod +x airtable-auto.py
          ./airtable-auto.py
          
      - name: Update master and prod
        run: |
          git fetch --all

          git add assets/data/medialist.json
          git commit -m "auto update news from airtable"

          git checkout master
          # Only update medialist.json 
          git checkout auto-add-news assets/data/medialist.json
          git commit -m "auto update news from airtable"
          git push origin master

          git branch -D auto-add-news
